// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abdzyspqaclwmmpywjpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZHp5c3BxYWNsd21tcHl3anBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTM0MDAsImV4cCI6MjA3Mzg4OTQwMH0.s3ZCshPZNjt7pJ2L0SbULrOSkqhZalHDqMMrKsBhjPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});